#!/bin/bash


docker build -t qcshop.azurecr.io/apigateway:latest -f "ApiGateway/Dockerfile" .
docker build -t qcshop.azurecr.io/catalogapi:latest -f "CatalogApi/Dockerfile" .

docker push qcshop.azurecr.io/apigateway:latest
docker push qcshop.azurecr.io/catalogapi:latest

az container delete --name QCMain --resource-group qcapp -y
az container create --resource-group qcapp --file deploy-main.yaml