#!/bin/bash

az container start --name QCmain --resource-group qcapp
az container start --name QCCatalog_Services --resource-group qcapp
az container start --name QCBasket_Services --resource-group qcapp