#!/bin/bash

docker build -t qcshop.azurecr.io/basketapi:latest -f "BasketApi/Dockerfile" .

docker push qcshop.azurecr.io/basketapi:latest

az container delete --name QCBasket_Services --resource-group qcapp -y
az container create --resource-group qcapp --file deploy-basket_services.yaml